// Code generated by protoc-gen-go. DO NOT EDIT.
// source: abi.proto

package abi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request from client
type CommandRequest struct {
	// Types that are valid to be assigned to RequestData:
	//	*CommandRequest_Hget
	//	*CommandRequest_Hgetall
	//	*CommandRequest_Hmget
	//	*CommandRequest_Hset
	//	*CommandRequest_Hmset
	//	*CommandRequest_Hdel
	//	*CommandRequest_Hmdel
	//	*CommandRequest_Hexist
	//	*CommandRequest_Hmexist
	RequestData          isCommandRequest_RequestData `protobuf_oneof:"request_data"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{0}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

type isCommandRequest_RequestData interface {
	isCommandRequest_RequestData()
}

type CommandRequest_Hget struct {
	Hget *Hget `protobuf:"bytes,1,opt,name=hget,proto3,oneof"`
}

type CommandRequest_Hgetall struct {
	Hgetall *Hgetall `protobuf:"bytes,2,opt,name=hgetall,proto3,oneof"`
}

type CommandRequest_Hmget struct {
	Hmget *Hmget `protobuf:"bytes,3,opt,name=hmget,proto3,oneof"`
}

type CommandRequest_Hset struct {
	Hset *Hset `protobuf:"bytes,4,opt,name=hset,proto3,oneof"`
}

type CommandRequest_Hmset struct {
	Hmset *Hmset `protobuf:"bytes,5,opt,name=hmset,proto3,oneof"`
}

type CommandRequest_Hdel struct {
	Hdel *Hdel `protobuf:"bytes,6,opt,name=hdel,proto3,oneof"`
}

type CommandRequest_Hmdel struct {
	Hmdel *Hmdel `protobuf:"bytes,7,opt,name=hmdel,proto3,oneof"`
}

type CommandRequest_Hexist struct {
	Hexist *Hexist `protobuf:"bytes,8,opt,name=hexist,proto3,oneof"`
}

type CommandRequest_Hmexist struct {
	Hmexist *Hmexist `protobuf:"bytes,9,opt,name=hmexist,proto3,oneof"`
}

func (*CommandRequest_Hget) isCommandRequest_RequestData() {}

func (*CommandRequest_Hgetall) isCommandRequest_RequestData() {}

func (*CommandRequest_Hmget) isCommandRequest_RequestData() {}

func (*CommandRequest_Hset) isCommandRequest_RequestData() {}

func (*CommandRequest_Hmset) isCommandRequest_RequestData() {}

func (*CommandRequest_Hdel) isCommandRequest_RequestData() {}

func (*CommandRequest_Hmdel) isCommandRequest_RequestData() {}

func (*CommandRequest_Hexist) isCommandRequest_RequestData() {}

func (*CommandRequest_Hmexist) isCommandRequest_RequestData() {}

func (m *CommandRequest) GetRequestData() isCommandRequest_RequestData {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *CommandRequest) GetHget() *Hget {
	if x, ok := m.GetRequestData().(*CommandRequest_Hget); ok {
		return x.Hget
	}
	return nil
}

func (m *CommandRequest) GetHgetall() *Hgetall {
	if x, ok := m.GetRequestData().(*CommandRequest_Hgetall); ok {
		return x.Hgetall
	}
	return nil
}

func (m *CommandRequest) GetHmget() *Hmget {
	if x, ok := m.GetRequestData().(*CommandRequest_Hmget); ok {
		return x.Hmget
	}
	return nil
}

func (m *CommandRequest) GetHset() *Hset {
	if x, ok := m.GetRequestData().(*CommandRequest_Hset); ok {
		return x.Hset
	}
	return nil
}

func (m *CommandRequest) GetHmset() *Hmset {
	if x, ok := m.GetRequestData().(*CommandRequest_Hmset); ok {
		return x.Hmset
	}
	return nil
}

func (m *CommandRequest) GetHdel() *Hdel {
	if x, ok := m.GetRequestData().(*CommandRequest_Hdel); ok {
		return x.Hdel
	}
	return nil
}

func (m *CommandRequest) GetHmdel() *Hmdel {
	if x, ok := m.GetRequestData().(*CommandRequest_Hmdel); ok {
		return x.Hmdel
	}
	return nil
}

func (m *CommandRequest) GetHexist() *Hexist {
	if x, ok := m.GetRequestData().(*CommandRequest_Hexist); ok {
		return x.Hexist
	}
	return nil
}

func (m *CommandRequest) GetHmexist() *Hmexist {
	if x, ok := m.GetRequestData().(*CommandRequest_Hmexist); ok {
		return x.Hmexist
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CommandRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CommandRequest_Hget)(nil),
		(*CommandRequest_Hgetall)(nil),
		(*CommandRequest_Hmget)(nil),
		(*CommandRequest_Hset)(nil),
		(*CommandRequest_Hmset)(nil),
		(*CommandRequest_Hdel)(nil),
		(*CommandRequest_Hmdel)(nil),
		(*CommandRequest_Hexist)(nil),
		(*CommandRequest_Hmexist)(nil),
	}
}

// Server response
type CommandResponse struct {
	// Status code, reuse HTTP 2xx/4xx/5xx code
	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Detail message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Values
	Values []*Value `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	// Kvpair
	Pairs                []*Kvpair `protobuf:"bytes,4,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{1}
}

func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (m *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(m, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CommandResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CommandResponse) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *CommandResponse) GetPairs() []*Kvpair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type Hget struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hget) Reset()         { *m = Hget{} }
func (m *Hget) String() string { return proto.CompactTextString(m) }
func (*Hget) ProtoMessage()    {}
func (*Hget) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{2}
}

func (m *Hget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hget.Unmarshal(m, b)
}
func (m *Hget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hget.Marshal(b, m, deterministic)
}
func (m *Hget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hget.Merge(m, src)
}
func (m *Hget) XXX_Size() int {
	return xxx_messageInfo_Hget.Size(m)
}
func (m *Hget) XXX_DiscardUnknown() {
	xxx_messageInfo_Hget.DiscardUnknown(m)
}

var xxx_messageInfo_Hget proto.InternalMessageInfo

func (m *Hget) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Hget) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Hgetall struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hgetall) Reset()         { *m = Hgetall{} }
func (m *Hgetall) String() string { return proto.CompactTextString(m) }
func (*Hgetall) ProtoMessage()    {}
func (*Hgetall) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{3}
}

func (m *Hgetall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hgetall.Unmarshal(m, b)
}
func (m *Hgetall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hgetall.Marshal(b, m, deterministic)
}
func (m *Hgetall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hgetall.Merge(m, src)
}
func (m *Hgetall) XXX_Size() int {
	return xxx_messageInfo_Hgetall.Size(m)
}
func (m *Hgetall) XXX_DiscardUnknown() {
	xxx_messageInfo_Hgetall.DiscardUnknown(m)
}

var xxx_messageInfo_Hgetall proto.InternalMessageInfo

func (m *Hgetall) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type Hmget struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hmget) Reset()         { *m = Hmget{} }
func (m *Hmget) String() string { return proto.CompactTextString(m) }
func (*Hmget) ProtoMessage()    {}
func (*Hmget) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{4}
}

func (m *Hmget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hmget.Unmarshal(m, b)
}
func (m *Hmget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hmget.Marshal(b, m, deterministic)
}
func (m *Hmget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hmget.Merge(m, src)
}
func (m *Hmget) XXX_Size() int {
	return xxx_messageInfo_Hmget.Size(m)
}
func (m *Hmget) XXX_DiscardUnknown() {
	xxx_messageInfo_Hmget.DiscardUnknown(m)
}

var xxx_messageInfo_Hmget proto.InternalMessageInfo

func (m *Hmget) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Hmget) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_String_
	//	*Value_Binary
	//	*Value_Integer
	//	*Value_Float
	//	*Value_Bool
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{5}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Value_Binary struct {
	Binary []byte `protobuf:"bytes,2,opt,name=binary,proto3,oneof"`
}

type Value_Integer struct {
	Integer int64 `protobuf:"varint,3,opt,name=integer,proto3,oneof"`
}

type Value_Float struct {
	Float float64 `protobuf:"fixed64,4,opt,name=float,proto3,oneof"`
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,5,opt,name=bool,proto3,oneof"`
}

func (*Value_String_) isValue_Value() {}

func (*Value_Binary) isValue_Value() {}

func (*Value_Integer) isValue_Value() {}

func (*Value_Float) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetString_() string {
	if x, ok := m.GetValue().(*Value_String_); ok {
		return x.String_
	}
	return ""
}

func (m *Value) GetBinary() []byte {
	if x, ok := m.GetValue().(*Value_Binary); ok {
		return x.Binary
	}
	return nil
}

func (m *Value) GetInteger() int64 {
	if x, ok := m.GetValue().(*Value_Integer); ok {
		return x.Integer
	}
	return 0
}

func (m *Value) GetFloat() float64 {
	if x, ok := m.GetValue().(*Value_Float); ok {
		return x.Float
	}
	return 0
}

func (m *Value) GetBool() bool {
	if x, ok := m.GetValue().(*Value_Bool); ok {
		return x.Bool
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_String_)(nil),
		(*Value_Binary)(nil),
		(*Value_Integer)(nil),
		(*Value_Float)(nil),
		(*Value_Bool)(nil),
	}
}

type Kvpair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *Value   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Kvpair) Reset()         { *m = Kvpair{} }
func (m *Kvpair) String() string { return proto.CompactTextString(m) }
func (*Kvpair) ProtoMessage()    {}
func (*Kvpair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{6}
}

func (m *Kvpair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kvpair.Unmarshal(m, b)
}
func (m *Kvpair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kvpair.Marshal(b, m, deterministic)
}
func (m *Kvpair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kvpair.Merge(m, src)
}
func (m *Kvpair) XXX_Size() int {
	return xxx_messageInfo_Kvpair.Size(m)
}
func (m *Kvpair) XXX_DiscardUnknown() {
	xxx_messageInfo_Kvpair.DiscardUnknown(m)
}

var xxx_messageInfo_Kvpair proto.InternalMessageInfo

func (m *Kvpair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Kvpair) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Hset struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Pair                 *Kvpair  `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hset) Reset()         { *m = Hset{} }
func (m *Hset) String() string { return proto.CompactTextString(m) }
func (*Hset) ProtoMessage()    {}
func (*Hset) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{7}
}

func (m *Hset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hset.Unmarshal(m, b)
}
func (m *Hset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hset.Marshal(b, m, deterministic)
}
func (m *Hset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hset.Merge(m, src)
}
func (m *Hset) XXX_Size() int {
	return xxx_messageInfo_Hset.Size(m)
}
func (m *Hset) XXX_DiscardUnknown() {
	xxx_messageInfo_Hset.DiscardUnknown(m)
}

var xxx_messageInfo_Hset proto.InternalMessageInfo

func (m *Hset) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Hset) GetPair() *Kvpair {
	if m != nil {
		return m.Pair
	}
	return nil
}

type Hmset struct {
	Table                string    `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Pairs                []*Kvpair `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Hmset) Reset()         { *m = Hmset{} }
func (m *Hmset) String() string { return proto.CompactTextString(m) }
func (*Hmset) ProtoMessage()    {}
func (*Hmset) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{8}
}

func (m *Hmset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hmset.Unmarshal(m, b)
}
func (m *Hmset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hmset.Marshal(b, m, deterministic)
}
func (m *Hmset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hmset.Merge(m, src)
}
func (m *Hmset) XXX_Size() int {
	return xxx_messageInfo_Hmset.Size(m)
}
func (m *Hmset) XXX_DiscardUnknown() {
	xxx_messageInfo_Hmset.DiscardUnknown(m)
}

var xxx_messageInfo_Hmset proto.InternalMessageInfo

func (m *Hmset) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Hmset) GetPairs() []*Kvpair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type Hdel struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hdel) Reset()         { *m = Hdel{} }
func (m *Hdel) String() string { return proto.CompactTextString(m) }
func (*Hdel) ProtoMessage()    {}
func (*Hdel) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{9}
}

func (m *Hdel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hdel.Unmarshal(m, b)
}
func (m *Hdel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hdel.Marshal(b, m, deterministic)
}
func (m *Hdel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hdel.Merge(m, src)
}
func (m *Hdel) XXX_Size() int {
	return xxx_messageInfo_Hdel.Size(m)
}
func (m *Hdel) XXX_DiscardUnknown() {
	xxx_messageInfo_Hdel.DiscardUnknown(m)
}

var xxx_messageInfo_Hdel proto.InternalMessageInfo

func (m *Hdel) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Hdel) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Hmdel struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hmdel) Reset()         { *m = Hmdel{} }
func (m *Hmdel) String() string { return proto.CompactTextString(m) }
func (*Hmdel) ProtoMessage()    {}
func (*Hmdel) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{10}
}

func (m *Hmdel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hmdel.Unmarshal(m, b)
}
func (m *Hmdel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hmdel.Marshal(b, m, deterministic)
}
func (m *Hmdel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hmdel.Merge(m, src)
}
func (m *Hmdel) XXX_Size() int {
	return xxx_messageInfo_Hmdel.Size(m)
}
func (m *Hmdel) XXX_DiscardUnknown() {
	xxx_messageInfo_Hmdel.DiscardUnknown(m)
}

var xxx_messageInfo_Hmdel proto.InternalMessageInfo

func (m *Hmdel) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Hmdel) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Hexist struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hexist) Reset()         { *m = Hexist{} }
func (m *Hexist) String() string { return proto.CompactTextString(m) }
func (*Hexist) ProtoMessage()    {}
func (*Hexist) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{11}
}

func (m *Hexist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hexist.Unmarshal(m, b)
}
func (m *Hexist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hexist.Marshal(b, m, deterministic)
}
func (m *Hexist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hexist.Merge(m, src)
}
func (m *Hexist) XXX_Size() int {
	return xxx_messageInfo_Hexist.Size(m)
}
func (m *Hexist) XXX_DiscardUnknown() {
	xxx_messageInfo_Hexist.DiscardUnknown(m)
}

var xxx_messageInfo_Hexist proto.InternalMessageInfo

func (m *Hexist) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Hexist) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Hmexist struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hmexist) Reset()         { *m = Hmexist{} }
func (m *Hmexist) String() string { return proto.CompactTextString(m) }
func (*Hmexist) ProtoMessage()    {}
func (*Hmexist) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f13b6186784fe43, []int{12}
}

func (m *Hmexist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hmexist.Unmarshal(m, b)
}
func (m *Hmexist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hmexist.Marshal(b, m, deterministic)
}
func (m *Hmexist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hmexist.Merge(m, src)
}
func (m *Hmexist) XXX_Size() int {
	return xxx_messageInfo_Hmexist.Size(m)
}
func (m *Hmexist) XXX_DiscardUnknown() {
	xxx_messageInfo_Hmexist.DiscardUnknown(m)
}

var xxx_messageInfo_Hmexist proto.InternalMessageInfo

func (m *Hmexist) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Hmexist) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*CommandRequest)(nil), "abi.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "abi.CommandResponse")
	proto.RegisterType((*Hget)(nil), "abi.Hget")
	proto.RegisterType((*Hgetall)(nil), "abi.Hgetall")
	proto.RegisterType((*Hmget)(nil), "abi.Hmget")
	proto.RegisterType((*Value)(nil), "abi.Value")
	proto.RegisterType((*Kvpair)(nil), "abi.Kvpair")
	proto.RegisterType((*Hset)(nil), "abi.Hset")
	proto.RegisterType((*Hmset)(nil), "abi.Hmset")
	proto.RegisterType((*Hdel)(nil), "abi.Hdel")
	proto.RegisterType((*Hmdel)(nil), "abi.Hmdel")
	proto.RegisterType((*Hexist)(nil), "abi.Hexist")
	proto.RegisterType((*Hmexist)(nil), "abi.Hmexist")
}

func init() { proto.RegisterFile("abi.proto", fileDescriptor_9f13b6186784fe43) }

var fileDescriptor_9f13b6186784fe43 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xdd, 0x34, 0x5f, 0x9b, 0xd9, 0xb2, 0x20, 0x6b, 0xb5, 0xb2, 0xb8, 0xb4, 0x58, 0x42, 0xea,
	0xa9, 0x02, 0xf6, 0x0a, 0x12, 0x5a, 0x2e, 0x95, 0xb8, 0xf9, 0xc0, 0x15, 0x39, 0x8a, 0x49, 0xa3,
	0x75, 0x92, 0x12, 0xbb, 0x2b, 0xf6, 0x2f, 0x70, 0xe0, 0x87, 0xf2, 0x2b, 0xd0, 0x8c, 0x9d, 0xa8,
	0x95, 0xb6, 0xa8, 0xa7, 0x66, 0xfc, 0xde, 0xbc, 0x89, 0xdf, 0x9b, 0x14, 0x0a, 0x55, 0x36, 0xeb,
	0xdd, 0xd0, 0xbb, 0x9e, 0xc5, 0xaa, 0x6c, 0xc4, 0xdf, 0x19, 0x5c, 0x7f, 0xe9, 0xdb, 0x56, 0x75,
	0x95, 0xd4, 0x3f, 0xf7, 0xda, 0x3a, 0xb6, 0x80, 0x64, 0x5b, 0x6b, 0xc7, 0xa3, 0x65, 0xb4, 0xba,
	0xfa, 0x50, 0xac, 0xb1, 0x63, 0x53, 0x6b, 0xb7, 0xb9, 0x90, 0x04, 0xb0, 0x15, 0xe4, 0xf8, 0xab,
	0x8c, 0xe1, 0x33, 0xe2, 0xcc, 0x27, 0x8e, 0x32, 0x66, 0x73, 0x21, 0x47, 0x98, 0x09, 0x48, 0xb7,
	0x2d, 0x6a, 0xc5, 0xc4, 0x03, 0xcf, 0x6b, 0xbd, 0x98, 0x87, 0x68, 0x9c, 0xd5, 0x8e, 0x27, 0x87,
	0xe3, 0x6c, 0x18, 0x67, 0xb5, 0xf3, 0x22, 0xc8, 0x48, 0x8f, 0x44, 0xec, 0x28, 0x62, 0x83, 0x48,
	0xa5, 0x0d, 0xcf, 0x0e, 0x45, 0x2a, 0x6d, 0x48, 0xa4, 0xd2, 0xe1, 0x4d, 0x90, 0x91, 0x1f, 0x89,
	0x78, 0x8a, 0x87, 0xd8, 0x5b, 0xc8, 0xb6, 0xfa, 0x57, 0x63, 0x1d, 0xbf, 0x24, 0xd2, 0x95, 0x27,
	0xd1, 0xd1, 0xe6, 0x42, 0x06, 0x90, 0xae, 0xdf, 0x7a, 0x5e, 0x71, 0x78, 0xfd, 0x76, 0x24, 0x8e,
	0xf0, 0xfd, 0x35, 0xcc, 0x07, 0x6f, 0xea, 0xf7, 0x4a, 0x39, 0x25, 0x7e, 0x47, 0xf0, 0x72, 0x32,
	0xdb, 0xee, 0xfa, 0xce, 0x6a, 0x76, 0x0b, 0x99, 0x75, 0xca, 0xed, 0x2d, 0xf9, 0xfd, 0x42, 0x86,
	0x8a, 0x71, 0xc8, 0x5b, 0x6d, 0xad, 0xaa, 0x35, 0x99, 0x5c, 0xc8, 0xb1, 0x64, 0x02, 0xb2, 0x47,
	0x65, 0xf6, 0xda, 0xf2, 0x78, 0x19, 0x4f, 0x77, 0xf9, 0x86, 0x47, 0x32, 0x20, 0xec, 0x0d, 0xa4,
	0x3b, 0xd5, 0x0c, 0x96, 0x27, 0x44, 0xf1, 0x37, 0xf9, 0xfa, 0x88, 0x67, 0xd2, 0x23, 0x62, 0x0d,
	0x09, 0x26, 0xc6, 0x6e, 0x20, 0x75, 0xaa, 0x34, 0x9a, 0xe6, 0x17, 0xd2, 0x17, 0xec, 0x15, 0xc4,
	0x0f, 0xfa, 0x29, 0x8c, 0xc6, 0x47, 0xb1, 0x80, 0x3c, 0x24, 0xfc, 0x7c, 0x8b, 0x78, 0x0f, 0x29,
	0x45, 0x7b, 0x42, 0x91, 0x41, 0xf2, 0xa0, 0x9f, 0x2c, 0x9f, 0x2d, 0xe3, 0x55, 0x21, 0xe9, 0x59,
	0xfc, 0x89, 0x20, 0xa5, 0x17, 0x67, 0x1c, 0x6d, 0x18, 0x9a, 0xae, 0xf6, 0x4d, 0x68, 0xb7, 0xaf,
	0x11, 0x29, 0x9b, 0x4e, 0x0d, 0xfe, 0x65, 0xe6, 0x88, 0xf8, 0x9a, 0xbd, 0x86, 0xbc, 0xe9, 0x9c,
	0xae, 0xf5, 0x40, 0xfb, 0x15, 0xa3, 0xf5, 0xe1, 0x80, 0xdd, 0x42, 0xfa, 0xc3, 0xf4, 0xca, 0xaf,
	0x55, 0x84, 0x19, 0x53, 0xc9, 0x6e, 0x20, 0x29, 0xfb, 0xde, 0xd0, 0x2e, 0x5d, 0xe2, 0x76, 0x60,
	0x75, 0x9f, 0x43, 0x4a, 0xc6, 0x89, 0x8f, 0x90, 0x79, 0x97, 0x46, 0x03, 0xa2, 0xc9, 0x00, 0xb6,
	0x0c, 0xa4, 0xb0, 0xf4, 0x87, 0xb6, 0x87, 0xee, 0x4f, 0x90, 0xe0, 0xe6, 0x9e, 0x30, 0x60, 0x01,
	0x09, 0x2a, 0x87, 0xf6, 0xa3, 0x48, 0x08, 0x10, 0x9f, 0xd1, 0xc0, 0xd3, 0xfd, 0x53, 0xa6, 0xb3,
	0xff, 0x66, 0x8a, 0x9b, 0x7c, 0x6e, 0xa6, 0x14, 0xd9, 0xe9, 0x86, 0xe7, 0x22, 0x7b, 0x07, 0x99,
	0xff, 0x22, 0xce, 0x1e, 0x72, 0x07, 0x79, 0xf8, 0x36, 0xce, 0x1f, 0x53, 0x66, 0xf4, 0x1f, 0x75,
	0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xc1, 0xd7, 0xa1, 0xb0, 0x04, 0x00, 0x00,
}
